export const monthlyPayments = [
  "Rent",
  "Mortgage",
  "Car Payment",
  "Car Insurance",
  "Health Insurance",
  "Phone Bill",
  "Internet",
  "Electric Bill",
  "Water Bill",
  "Gas Bill",
  "Trash Collection",
  "Netflix",
  "Hulu",
  "Disney+",
  "Max",
  "Amazon Prime",
  "Spotify",
  "Apple Music",
  "YouTube Premium",
  "Google One",
  "iCloud Storage",
  "Dropbox",
  "Adobe Creative Cloud",
  "Microsoft 365",
  "Gym Membership",
  "Peloton",
  "Planet Fitness",
  "Personal Trainer",
  "Student Loan",
  "Credit Card Payment",
  "Loan Payment",
  "Life Insurance",
  "Pet Insurance",
  "Security System (e.g. ADT, Ring)",
  "SiriusXM",
  "Audible",
  "Language Learning App (e.g. Duolingo, Babbel)",
  "Meditation App (e.g. Headspace, Calm)",
  "Online Course Subscription (e.g. Coursera, Udemy Plus)",
  "Gaming Subscription (e.g. Xbox Game Pass, PlayStation Plus)",
  "Streaming Bundle (e.g. Hulu + Disney+ + ESPN)",
  "Meal Kit Service (e.g. HelloFresh, Blue Apron)",
  "Coffee Subscription",
  "Cloud Gaming (e.g. NVIDIA GeForce Now)",
  "News Subscription (e.g. NYTimes, WSJ)",
  "Dating App Subscription (e.g. Tinder Gold, Bumble Boost)",
  "VPN Service",
  "Stock Photo Subscription (e.g. Shutterstock)",
  "Online Therapy (e.g. BetterHelp)",
  "Fitness App (e.g. MyFitnessPal Premium)",
  "Cloud Storage for Photos",
  "Donation/Charity Subscription",
  "Patreon",
  ,
  "Substack",
  "Home Cleaning Service",
  "Lawn Care Service",
  "Homeowners Association Fee (HOA)",
  "Childcare",
  "Private Tutor",
  "Coworking Space Membership",
];
